name: PR Labeler
on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Add label
        uses: actions/github-script@v5
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const issue_number = context.issue.number;
            const repository = context.repo;
            github.issues.addLabels({
              ...repository,
              issue_number: issue_number,
              labels: ['bitmap']
            });