# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

name: Check Thrift Changes

on:
  pull_request:
    branches:
      - master

jobs:
  check-thrift-changes:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check Thrift changes
      run: |
        # 获取所有更改的Thrift文件
        changed_files=$(git diff --name-only origin/<target-branch> HEAD | grep ".thrift$")
        # 如果没有Thrift文件更改，则退出脚本
        if [[ -z "$changed_files" ]]
        then
          echo "No Thrift files have been changed"
          exit 0
        fi

        # 循环检查每个更改的Thrift文件
        for file in $changed_files
        do
          # 提取文件名和文件路径
          file_name=$(basename $file)
          file_path=$(dirname $file)

          # 判断Thrift是新增字段还是新增结构
          if grep -qP "struct $file_name\b" $file
          then
            echo "Thrift新增结构 $file_name"
          else
            # get new field
            new_field=$(diff <(grep -oP 'struct \K\w+' $file_path/$file_name) <(grep -oP 'struct \K\w+' $file) | grep '>' | grep -oP '\.\K\w+')
            # check new field required
            is_required=$(grep -oP "required \K$new_field" $file)
            if [[ "$is_required" == "required" ]]
            then
              echo "Thrift new field $new_field is required"
              exit 1
            fi
            # 检查是否删除了字段
            deleted_fields=$(diff <(grep -oP 'struct \K\w+' $file_path/$file_name) <(grep -oP 'struct \K\w+' $file) | grep '<' | grep -oP '\.\K\w+')
            if [[ -n "$deleted_fields" ]]
            then
              echo "Thrift shouldn't $deleted_field"
              exit 1
            fi
          fi
        done
