# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
---
name: Latest-Master-Code-Check
on:
  pull_request:
  pull_request_review:
    types: [submitted]
  push:
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Add remote and fetch main branch
        run: |
          git remote add main https://github.com/apache/doris.git
          git fetch main master

      - name: Check if code includes latest code of master branch
        run: |
          if [[ $(git merge-base --is-ancestor FETCH_HEAD HEAD) ]]; then
            echo "Code does not include latest code of master branch"
            exit 1
          else
            echo "Code includes latest code of master branch"
          fi